export const ENTREPRISES_PREDEFINIES = [
  'Microsoft',
  'Apple',
  'Google',
  'Amazon',
  'Mojang',
  'Nvidia',
  'Intel',
  'AMD',
  'LCL',
  'Orange',
  'Dell',
  'Toshiba',
  'Salesforce',
  'Amadeus',
  'HPE',
  'Adobe',
  'VMware',
  'IntelliJ',
  'PayPal',
  'eBay',
  'LinkedIn',
  'YouTube',
  'Back Market',
  'Google Cloud',
  'Oracle',
  'Dropbox',
  'Unity',
  'Thales',
  'IBM',
  'Mozilla',
  'Fnac',
  'Ubisoft',
  'OVHcloud',
  'Hostinger',
  'Perplexity',
  'Meta',
  'Ionos',
  'Decathlon',
  'OpenAI',
  'Sum-up',
  'Stripe',
  'Klarna',
  'Safran',
  'Endered',
  'Algeria Group',
  'DC2 Scale',
  'Appcraft',
  'Econom',
  'Free',
  'Mastercard',
  'MSI',
  'Corsair',
  'Algolia',
  'Lockself',
  'Verisure',
  'Docaposte',
  'Mawaqit',
  'Xiaomi',
  'Samsung',
  'Engie',
  'Discord',
  'Bloomberg',
  'Red Hat',
  'Cisco',
  'La Poste',
  'Digipost',
  'Pluxee'
]

export const POSTES_PREDEFINIES = [
  'Développeur Full Stack',
  'Développeur Frontend',
  'Développeur Backend',
  'Développeur Mobile',
  'DevOps Engineer',
  'Data Scientist',
  'Product Manager',
  'UX/UI Designer',
  'Architecte Logiciel',
  'Chef de Projet IT',
  'Ingénieur Cybersécurité',
  'Analyste Données',
  'Consultant IT',
  'Administrateur Système',
  'Ingénieur Cloud',
  'Développeur React',
  'Développeur Angular',
  'Développeur Vue.js',
  'Développeur Node.js',
  'Développeur Python',
  'Développeur Java',
  'Développeur C#',
  'Développeur PHP',
  'Ingénieur Machine Learning',
  'Scrum Master',
  'Product Owner',
  'Business Analyst',
  'QA Engineer',
  'Testeur Logiciel',
  'Ingénieur Réseau'
]